const constant = {
  PRODUCTION: 'production',
  DEVELOPMENT: 'development',
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_INSERTED: 201,
  HTTP_STATUS_INTERNAL_ERROR: 500,
  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_UNAUTHORIZED: 401,
  HTTP_STATUS_TOKEN: 403,
  SALT_ROUNDS: 10,
  FOUNDING_MEMBER_FEATURE: true,
  MAX_FOUNDING_MEMBERS: 1000,
  FOUNDING_MEMBER: 'FOUNDING_MEMBER',
  USER_IN_WAITLIST: 'USER_IN_WAITLIST',
  USER_NOT_FOUND: 'User not Found',
  USER_CREATED_MSG: 'User Created',
  SUCCESS: 'success',
  LOGIN_SUCCESSFUL: 'Login Successfull',
  INCORRECT_LOGIN: 'The email or password you entered is incorrect. Please try something else.',
  CODE_SENT_SUCCESSFUL: 'We have e-mailed your password reset link!',
  CODE_EXPIRED: 'Link has been expired!',
  PASSWORD_CHANGE_SUCCESS: 'Your password has been changed, you can now go back to the Frolo app and log in',
  EMAIL_SENT_SUCCESSFUL: 'We have e-mailed your verify email link!',
  ACCOUNT_ALREADY_EXISTS: 'This account already exists, please try signing in',
  OTHER_LOGIN_METHOD: 'You already have an account with another login method',
  PASSWORD_INVALID: 'Invalid Password. Please enter a valid password.',
  NOT_ABLE_TO_SIGNUP: 'Not able to signup. Please try again later.',
  USER_DETAILS_UPDATED: 'User details updated successfully',
  USER_DETAILS_RECEIVED: 'User details received successfully',
  // eslint-disable-next-line @typescript-eslint/quotes
  ABOUT_CHILDREN_UPDATED: "User's children information updated successfully",
  // eslint-disable-next-line @typescript-eslint/quotes
  CHILDREN_NUMBER_MISMATCH: "The no. of children and the children's details do not match.",
  ONBOARD_GET_DATA_SUCCESS: 'Successfully Get Onboarding Data',
  SOMETHING_WENT_WRONG: 'Something went Wrong',
  ONBOARD_DATA_SAVED: 'Onboarding data saved successfully',
  FOUNDING_MEMBERS_DETAILS_RECEIVED: 'Founding members details received successfully.',
  ANDROID_REDIRECT_URI: 'https://play.google.com/store/apps/details?id=com.froloapp',
  IOS_REDIRECT_URI: 'https://itunes.apple.com/gb/app/frolo/id1469900100?mt=8',
  USERNAME_UPDATED: 'Username updated',
  SUB_ID_REQUIRED: 'Sub Id required',
  SOCIAL_ID_REQUIRED: 'Social id required',
  ACCOUNTTYPE_REQUIRED: 'account_type is required',
  USERNAME_REQUIRED: 'Username Required',
  TYPE_USERNAME: 'Username must be a string',
  REASON_REQUIRED: 'Reason is required',
  OPTION_ID_REQUIRED: 'Option id is required',
  TYPE_REASON: 'Reason must be string',
  FUTURE_ANNOUNCEMENTS_REQUIRED: 'Future announcement is required',
  TYPE_FUTURE_ANNOUNCEMENTS: 'Future announcement should be number',
  QUESTION_TYPE_REQUIRED: 'Question type is required',
  USER_NOT_FOUND_DATING: 'User does not exist on dating',
  EMAIL_REQUIRED: 'Email is required',
  TYPE_EMAIL: 'Invalid email. Please enter a valid email address.',
  EMAIL_INVALID: 'Invalid email',
  GIVEN_NAME_REQUIRED: 'Username is required',
  GIVEN_NAME_INVALID: 'Invalid username',
  PASSWORD_REQUIRED: 'Password is required',
  TYPE_PASSWORD: 'Invalid Password',
  MIN_LENGTH_PASSWORD: 'Minimum length of password should be 8 characters',
  LOGIN_METHOD_REQUIRED: 'Login method is required',
  TYPE_LOGIN_METHOD: 'Login method must be a string',
  USER_INVISISBLE_SUCCESS: 'User is invisible successfully',
  USER_VISISBLE_SUCCESS: 'User is visible successfully',
  USER_DELETED_SUCCESS: 'User account is deleted successfully',
  EMAIL_PASSWORD_MISMATCH: 'The email or password you entered is incorrect. Please try something else.',
  AGE_REQUIRED: 'Age is required',
  TYPE_AGE: 'Invalid age type',
  MIN_AGE: 'Minimum age of the user should be 18',
  GENDER_REQUIRED: 'Gender is required',
  TYPE_GENDER: 'Gender must be a string',
  POSTCODE_REQUIRED: 'Postcode is required',
  TYPE_POSTCODE: 'Postcode must be a string',
  INVALID_POSTCODE: 'Please enter a valid postcode(LONDON or IRELAND Only).',
  HEIGHT_REQUIRED: 'Height is required',
  TYPE_HEIGHT: 'Height must be a number',
  FIRST_NAME_REQUIRED: 'First name is required',
  TYPE_FIRST_NAME: 'First name must be a string',
  LAST_NAME_REQUIRED: 'Last name is required',
  TYPE_LAST_NAME: 'Last name must be a string',
  LATITUDE_REQUIRED: 'Latitude is required',
  TYPE_LATITUDE: 'Latitude must be a valid number',
  LONGITUDE_REQUIRED: 'Longitude is required',
  TYPE_LONGITUDE: 'Longitude must be a valid number',
  PROFILE_PICTURES_REQUIRED: 'Profile pictures required',
  TYPE_PROFILE_PICTURES: 'Profile pictures must be in an array',
  CHILDREN_NUMBER_REQUIRED: 'Children number is required',
  TYPE_CHILDREN_NUMBER: 'Children number must be a number',
  CHILDREN_DETAILS_REQUIRED: 'Children details are required',
  TYPE_CHILDREN_DETAILS: 'Children details must be in an array',
  PAUSE_ALL_REQUIRED: 'Pause all is required',
  TYPE_PAUSE_ALL: 'This must be a number',
  PAGE_REQUIRED: 'Page is required',
  TYPE_PAGE: 'Page must be string',
  INVALID_TOKEN: 'Invalid Token',
  INVALID_TOKEN_LOGOUT: 'It is not possible for you to access the Frolo at this time',
  FORCE_DOWNLOAD_REQUIRED:
    // eslint-disable-next-line max-len
    'You are using an unsupported version of the Frolo App, please update to the latest version to get the best experience.',
  INTERNAL_SERVER_ERROR: 'Some error occured',
  PARENTING_INFO: 'PARENTING_INFO',
  WORKING_INFO: 'WORKING_INFO',
  LIMIT_REQUIRED: 'Limit is required',
  DAY_REQUIRED: 'Day is required',
  IS_SUSPENDED_REQUIRED: 'Is Suspended is required',
  SOCIAL_SIGNUP_MIGRATION_ERROR: 'This email id was used to sign in with another method',
  USER_EXPORT_ADMIN_EMAIL_TEMPLATE: 'user-export-email',
  USER_EXPORT_ADMIN_EMAIL_SUBJECT: 'Frolo: User export ready for download',
  VALIDATE_EMAIL_ERROR: 'An account with this email address already exists, please try something else',
  MODE_REQUIRED: 'Mode is required',
  MODE_TYPE: 'Mode must be string',
  MODE_VALID: 'Mode must be [COMMUNITY/DATING]',
  APPLICATION_REQUIRED: 'Application is required',
  APPLICATION_TYPE: 'Application must be string',
  APPLICATION_VALID: 'Application must be [COMMUNITY/DATING/BOTH]',
  USER_ID_REQUIRED: 'User id is required',
  BLOCK_MODERATOR: 'You can not block a moderator user.',
  USER_ID_GUID: 'User ID must be a valid UUID',
  INVALID_DEVICE_ID: 'Invalid device id',
  REQUIRED_USER_ID: 'User ID is required and cannot be empty',
  TYPE_USER_ID: 'User ID must be a string',
  GUID_USER_ID: 'User ID must be a valid UUID',
  USER_REPORTED: 'User reported successfully',
  DATING_USER_TYPE: 'Dating',
  ALREADY_REPORTED: 'You have already reported this user',
  USER_ENTITY_TYPE: 'USER',
  USER_REPORT_ADMIN_EMAIL_TEMPLATE: 'user-report-email',
  USER_REPORT_ADMIN_EMAIL_SUBJECT: 'Dating user reported',

  // typeorm errors
  ER_DUP_ENTRY: 'ER_DUP_ENTRY',
  LIKE_USER_ID_REQUIRED: 'Like id is required',
  USER_ID_TYPE: 'Like id must be string',
  LIKE_TYPE_REQUIRED: 'Type is requred',
  LIKE_TYPE_ERROR: 'Like type must be string',
  LIKE_TYPE_ENUM: 'Type must  be [LIKE/DISLIKE/MATCHED/REJECTED]',
  INAVLID_MATCHED: 'Invalid matched',
  INAVLID_LIKE: 'Multiple like/dislike not possible',
};

export default constant;
