import { config as dotenvConfig } from 'dotenv';

dotenvConfig();

export const ENVIRONMENT = process.env.NODE_ENV;
export const TYPEORM_HOST = process.env.TYPEORM_HOST;
export const TYPEORM_USERNAME = process.env.TYPEORM_USERNAME;
export const TYPEORM_PASSWORD = process.env.TYPEORM_PASSWORD;
export const TYPEORM_DATABASE = process.env.TYPEORM_DATABASE;
export const TYPEORM_PORT = process.env.TYPEORM_PORT;
export const TYPEORM_LOGGING = process.env.TYPEORM_LOGGING;
export const JWT_SECRET = process.env.JWT_SECRET;
export const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
export const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
export const SWAGGER_BASE_URL = process.env.SWAGGER_BASE_URL;
export const PORT = process.env.PORT;
export const SENTRY_DSN = process.env.SENTRY_DSN;
export const AWS_COGNITO_USER_POOL_ID = process.env.AWS_COGNITO_USER_POOL_ID as string;
export const AWS_COGNITO_USER_POOL_CLIENT_ID: string = process.env.AWS_COGNITO_USER_POOL_CLIENT_ID as string;
export const AWS_API_VERSION = process.env.AWS_API_VERSION;
export const AWS_COGNITO_USER_POOL_REGION = process.env.AWS_COGNITO_USER_POOL_REGION;
export const AWS_S3_REGION = process.env.AWS_S3_REGION;
export const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;
export const AWS_BUCKET_FOLDER = process.env.AWS_BUCKET_FOLDER as string;
export const IMAGE_BASE_URL = process.env.IMAGE_BASE_URL as string;
export const SYNC_BCRYPT = process.env.SYNC_BCRYPT ? process.env.SYNC_BCRYPT : false;
export const REDIS_HOST = process.env.REDIS_HOST;
export const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
export const REDIS_PORT = process.env.REDIS_PORT as string;
export const CACHE_KEY = process.env.CACHE_KEY as string;
export const CACHE_BASE_KEY = process.env.CACHE_BASE_KEY as string;
export const COMMUNITY_API_TOKEN = process.env.COMMUNITY_API_TOKEN as string;
export const EXPORT_CSV_MAX_CALL = (process.env.EXPORT_CSV_MAX_CALL as unknown) as number;
export const EXPORT_CSV_WAIT_TIME = (process.env.EXPORT_CSV_WAIT_TIME as unknown) as number;
export const SES_AWS_REGION = process.env.SES_AWS_REGION;
export const SES_FROM_EMAIL = process.env.SES_FROM_EMAIL as string;
export const ADMIN_EMAIL = process.env.ADMIN_EMAIL as string;
export const COMMUNITY_BASE_URL = process.env.COMMUNITY_BASE_URL as string;
export const BLOCK_USER_PATH = process.env.BLOCK_USER_PATH as string;
export const ES_HOST = process.env.ES_HOST;
export const MAINTANANCE_MODE = process.env.MAINTANANCE_MODE;
export const MAILCHIMP_API_KEY = process.env.MAILCHIMP_API_KEY as string;
export const MAILCHIMP_SERVER = process.env.MAILCHIMP_SERVER as string;
export const MAILCHIMP_LIST_ID = process.env.MAILCHIMP_LIST_ID as string;
export const ENV_TYPE = process.env.ENV_TYPE as string;
export const INDEX_NAME = `dating_users_${ENV_TYPE}`;
